USE [master]
GO
/****** Object:  Database [Party]    Script Date: 21-Jul-23 6:08:04 PM ******/
CREATE DATABASE [Party]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Party', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Party.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Party_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Party_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Party] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Party].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Party] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Party] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Party] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Party] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Party] SET ARITHABORT OFF 
GO
ALTER DATABASE [Party] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Party] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Party] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Party] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Party] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Party] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Party] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Party] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Party] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Party] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Party] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Party] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Party] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Party] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Party] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Party] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Party] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Party] SET RECOVERY FULL 
GO
ALTER DATABASE [Party] SET  MULTI_USER 
GO
ALTER DATABASE [Party] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Party] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Party] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Party] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Party] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Party] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Party', N'ON'
GO
ALTER DATABASE [Party] SET QUERY_STORE = OFF
GO
USE [Party]
GO
/****** Object:  Table [dbo].[Address]    Script Date: 21-Jul-23 6:08:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Address](
	[id] [int] NULL,
	[address] [text] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Admin]    Script Date: 21-Jul-23 6:08:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[id] [int] NULL,
	[username] [nvarchar](150) NULL,
	[password] [nvarchar](150) NULL,
	[name] [nvarchar](150) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 21-Jul-23 6:08:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](150) NOT NULL,
	[age] [int] NULL,
	[address] [int] NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Address] ([id], [address]) VALUES (1, N'135 Nguyen Xi')
GO
INSERT [dbo].[Address] ([id], [address]) VALUES (2, N'11 duong so 85')
GO
INSERT [dbo].[Address] ([id], [address]) VALUES (3, N'35 Dinh van Dieu')
GO
INSERT [dbo].[Admin] ([id], [username], [password], [name]) VALUES (1, N'hiep', N'123', N'hiep')
GO
INSERT [dbo].[Admin] ([id], [username], [password], [name]) VALUES (2, N'bao', N'1', N'bao')
GO
SET IDENTITY_INSERT [dbo].[Person] ON 
GO
INSERT [dbo].[Person] ([id], [name], [age], [address]) VALUES (2, N'bao', 22, 3)
GO
INSERT [dbo].[Person] ([id], [name], [age], [address]) VALUES (3, N'bao ne 3', 21, 1)
GO
INSERT [dbo].[Person] ([id], [name], [age], [address]) VALUES (5, N'baone', 123, 1)
GO
SET IDENTITY_INSERT [dbo].[Person] OFF
GO
USE [master]
GO
ALTER DATABASE [Party] SET  READ_WRITE 
GO
